version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    container_name: usuario_biblioteca_api_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: postgres:latest
    container_name: usuario_postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - usuario_postgres_data:/var/lib/postgresql

volumes:
  usuario_postgres_data:
